project:
  type: website

website:
  title: "AHEAD Database"
  navbar:
    background: "#5544cc"
    left:
      - href: qmd/index.qmd
        text: Home
      - href: qmd/indicators.qmd
        text: Indicators
      - href: qmd/references.qmd
        text: References
  page-footer:
    background: "#5544cc"
    left: |
      Copyright 2026 Ahead | All Rights Reserved
    right:
      - href: https://github.com/BiodataAnalysisGroup/ahead-resources
        icon: github
        aria-label: GitHub
      - href: https://www.linkedin.com/company/ahead-project-msca/
        icon: linkedin
        aria-label: LinkedIn
    center: |
      The research leading to these results has received funding from the Horizon Europe Programme under the Marie Sk≈Çodowska-Curie grant agreement No 101183031.

format:
  html:
    theme:
      light: [cosmo, scss/light-theme.scss]
    css: scss/styles.css
    toc: false
    minimal: false
    smooth-scroll: true
    




editor: visual

